version: '3.5'

services:
  web:
    image: jrobinsonc/php:7.3-apache
    ports:
      - 80
      - 443
    volumes:
      - ./app:/var/www/html
    environment:
      - APP_ENV
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_USER
    depends_on:
      - db

  db:
    image: mariadb:10
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_USER
    ports:
      - 3306

volumes:
  db-data:
