version: '3.5'

services:
  web:
    build: .
    ports:
      - 80
      - 443
    volumes:
      - ./app:/var/www/html
      - ./logs:/var/www/logs
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_USER

  db:
    image: mariadb:10
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_USER
    ports:
      - 3306

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025

  adminer:
    image: adminer
    ports:
      - 8080
